import { library } from "@fortawesome/fontawesome-svg-core";
import { faCircle as farCircle } from "@fortawesome/free-regular-svg-icons";
import {
  faArrowLeft,
  faArrowRight,
  faChevronCircleUp,
  faChevronLeft,
  faChevronRight,
  faCircle,
  faEllipsisH,
  faEnvelope,
  faExclamation,
  faGlobe,
  faInfo,
  faKhanda,
  faLayerGroup,
  faRecycle,
  faSadCry,
  faSearch,
  faToggleOff,
  faToggleOn,
  faTrophy,
  faUndo,
  faUsers,
  faUserShield
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faArrowLeft,
  faArrowRight,
  faChevronCircleUp,
  faChevronLeft,
  faChevronRight,
  faCircle,
  farCircle,
  faEllipsisH,
  faEnvelope,
  faExclamation,
  faGlobe,
  faInfo,
  faKhanda,
  faLayerGroup,
  faRecycle,
  faSadCry,
  faSearch,
  faToggleOff,
  faToggleOn,
  faTrophy,
  faUndo,
  faUsers,
  faUserShield
);
